name: 'Terraform Deploy'

# Manual trigger with inputs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      destroy:
        description: 'Choose if you want to destroy resources'
        required: false
        default: 'false'
        type: boolean

jobs:
  terraform:
    name: 'Deploy Infrastructure'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Azure Login using secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0 # Update to the latest stable version as needed

    - name: Terraform Init
      run: terraform init
      env:
        TF_LOG: DEBUG # Optional: Set this to DEBUG for more detailed logs

    # Conditional step to either apply or destroy resources
    - name: Terraform Plan
      run: |
        if [[ "${{ github.event.inputs.destroy }}" == "true" ]]; then
          terraform plan -destroy -var-file="env-${{ github.event.inputs.environment }}.tfvars"
        else
          terraform plan -var-file="env-${{ github.event.inputs.environment }}.tfvars"
        fi

    - name: Terraform Apply or Destroy
      run: |
        if [[ "${{ github.event.inputs.destroy }}" == "true" ]]; then
          terraform destroy -auto-approve -var-file="env-${{ github.event.inputs.environment }}.tfvars"
        else
          terraform apply -auto-approve -var-file="env-${{ github.event.inputs.environment }}.tfvars"
        fi

    # Show generated admin password output securely
    - name: Show Generated Admin Password
      if: github.event.inputs.destroy == 'false'
      run: terraform output -raw admin_password
      env:
        TF_LOG: DEBUG # Optional: Set this to DEBUG for more detailed logs
